.PHONY=solve-a

solve-a:
	elixir ./solution_a.exs

practice-a:
	elixir ./solution_a.exs input_example_a.txt

solve-b:
	elixir ./solution_b.exs

practice-b:
	elixir ./solution_b.exs input_example_b.txt
